### ISSUE TITLE
Nextssh 应用打开之后白屏

### ISSUE THREAD

**Issue by southcat** [zhshch2002/xzhshch-beaudar#2]
Windows10 上个版本出现的问题 一直可以正常使用然后有一天打开就白屏了  什么都不显示

**Comment by zhshch2002** [comment]
有关软件具体的使用问题或者报错还请使用页面的对话功能，或联系软件内设置界面留下的邮箱。

遇到共性或者软件本身Bug我会在网站上公告并在tg频道内通知。

我也联络了您网站上留下的tg，本issue就先关闭了。
